# Generated by Django 5.0.6 on 2024-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='blog/media', verbose_name='изображение')),
                ('publish', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('view_counter', models.PositiveIntegerField(default=0, help_text='укажите количество просмотров', verbose_name='счетчик проcмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
