# Generated by Django 5.0.6 on 2024-06-07 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufactured_at',
            field=models.DateField(default=datetime.date(2024, 6, 7)),
        ),
    ]
