# Generated by Django 5.0.6 on 2024-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufactured_at',
            field=models.DateField(help_text='Введите дату производства продукта', null=True, verbose_name='Дата производства продукта'),
        ),
    ]
