# Generated by Django 5.0.6 on 2024-07-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_products_view_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=100, verbose_name='Наименование')),
                ('version_number', models.PositiveIntegerField(help_text='введите номер версии', max_length=3, verbose_name='номер версии')),
                ('version_name', models.CharField(help_text='введите наименование версии', max_length=100, verbose_name='наименование версии')),
                ('current_version', models.BooleanField(default=False, verbose_name='Признак текущей версии')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версиии',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию из списка', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalog.category', verbose_name='Категория'),
        ),
    ]
