# Generated by Django 5.0.6 on 2024-07-11 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_productversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='введите номер версии', verbose_name='номер версии')),
                ('version_name', models.CharField(help_text='введите наименование версии', max_length=100, verbose_name='наименование версии')),
                ('current_version', models.BooleanField(default=False, verbose_name='Признак текущей версии')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalog.products', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версиии',
            },
        ),
    ]
