# Generated by Django 5.0.6 on 2024-07-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productversion"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductVersion",
            new_name="ProductVersions",
        ),
        migrations.AlterModelOptions(
            name="productversions",
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
            },
        ),
    ]
